
import React, { createContext, useContext, useEffect, useState } from 'react';
import { useLocation } from 'react-router-dom';
import { db } from '../lib/firebase';

interface StyleOverride {
  selector: string;
  styles: Record<string, string>;
  text?: string;
}

interface VisualEditContextType {
  isEditing: boolean;
  overrides: StyleOverride[];
  toggleEditMode: () => void;
  saveOverride: (override: StyleOverride) => void;
  saveAllChanges: () => Promise<void>;
  loading: boolean;
}

const VisualEditContext = createContext<VisualEditContextType>({
  isEditing: false,
  overrides: [],
  toggleEditMode: () => {},
  saveOverride: () => {},
  saveAllChanges: async () => {},
  loading: true,
});

export const useVisualEdit = () => useContext(VisualEditContext);

export const VisualEditProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [isEditing, setIsEditing] = useState(false);
  const [overrides, setOverrides] = useState<StyleOverride[]>([]);
  const [loading, setLoading] = useState(true);
  const location = useLocation();

  // 1. Activate Edit Mode from URL
  useEffect(() => {
    const params = new URLSearchParams(location.search);
    if (params.get('visualEdit') === 'true') {
      setIsEditing(true);
    } else {
      setIsEditing(false);
    }
  }, [location]);

  // 2. Fetch Overrides from Firebase on Mount
  useEffect(() => {
    const fetchOverrides = async () => {
      try {
        const doc = await db.collection('site_settings').doc('visual_overrides').get();
        if (doc.exists) {
          const data = doc.data();
          if (data && data.overrides) {
            setOverrides(data.overrides);
          }
        }
      } catch (error) {
        console.error("Error loading visual overrides:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchOverrides();
  }, []);

  // 3. Inject CSS Styles into <head> (Handles CSS Persistence)
  useEffect(() => {
    const styleId = 'visual-editor-global-styles';
    let styleTag = document.getElementById(styleId);
    
    if (!styleTag) {
      styleTag = document.createElement('style');
      styleTag.id = styleId;
      document.head.appendChild(styleTag);
    }

    let css = '/* Generated by Shamsia Visual Editor */\n';
    overrides.forEach(item => {
      const styleString = Object.entries(item.styles)
        .map(([key, value]) => {
            // Ensure !important is present to override Tailwind
            const val = value.includes('!important') ? value : `${value} !important`;
            return `${key}: ${val};`;
        })
        .join(' ');
      
      if (styleString) {
        css += `${item.selector} { ${styleString} }\n`;
      }
    });

    styleTag.textContent = css;
  }, [overrides]);

  // 4. Apply Text Content Overrides (Handles React Re-renders)
  useEffect(() => {
    const applyTextOverrides = () => {
        overrides.forEach(override => {
            if (override.text !== undefined && override.text !== null) {
                const elements = document.querySelectorAll(override.selector);
                elements.forEach(el => {
                    // Only replace if strictly necessary to avoid cursor jumping during edit
                    // and check if it has a single text node to avoid destroying icons/nested html
                    if (el instanceof HTMLElement) {
                         if (el.innerText !== override.text) {
                             // Use innerText to preserve line breaks, but be careful with nested tags
                             // If element has children tags, we might be breaking layout.
                             // Safe check: only if children count is 0 or it was previously edited
                             if (el.children.length === 0 || el.getAttribute('data-visual-edited') === 'true') {
                                 el.innerText = override.text as string;
                                 el.setAttribute('data-visual-edited', 'true');
                             }
                         }
                    }
                });
            }
        });
    };

    // Run immediately
    applyTextOverrides();

    // Run on an interval to catch client-side routing changes or re-renders
    const intervalId = setInterval(applyTextOverrides, 500);
    return () => clearInterval(intervalId);
  }, [overrides, location.pathname]); // Re-run when path changes


  const saveOverride = (newOverride: StyleOverride) => {
    setOverrides(prev => {
      const updated = [...prev];
      const index = updated.findIndex(o => o.selector === newOverride.selector);
      
      if (index > -1) {
        updated[index] = {
            ...updated[index],
            styles: { ...updated[index].styles, ...newOverride.styles },
            text: newOverride.text !== undefined ? newOverride.text : updated[index].text
        };
      } else {
        updated.push(newOverride);
      }
      return updated;
    });
  };

  const saveAllChanges = async () => {
    try {
      // Remove any overrides that are empty
      const cleanOverrides = overrides.filter(o => 
        (Object.keys(o.styles).length > 0) || (o.text !== undefined && o.text !== '')
      );
      
      await db.collection('site_settings').doc('visual_overrides').set(
        { overrides: cleanOverrides }, 
        { merge: true }
      );
      console.log("Visual overrides saved to Firebase successfully.");
    } catch (e) {
      console.error("Failed to save all changes to Firebase", e);
      throw e;
    }
  };

  const toggleEditMode = () => setIsEditing(!isEditing);

  return (
    <VisualEditContext.Provider value={{ isEditing, overrides, toggleEditMode, saveOverride, saveAllChanges, loading }}>
      {children}
    </VisualEditContext.Provider>
  );
};
