
import React, { createContext, useContext, useEffect, useState, useRef } from 'react';
import { useLocation } from 'react-router-dom';
import { db } from '../lib/firebase';

interface StyleOverride {
  selector: string;
  styles: Record<string, string>;
  text?: string;
}

interface VisualEditContextType {
  isEditing: boolean;
  overrides: StyleOverride[];
  toggleEditMode: () => void;
  saveOverride: (override: StyleOverride) => void;
  saveAllChanges: () => Promise<void>;
  loading: boolean;
}

const VisualEditContext = createContext<VisualEditContextType>({
  isEditing: false,
  overrides: [],
  toggleEditMode: () => {},
  saveOverride: () => {},
  saveAllChanges: async () => {},
  loading: true,
});

export const useVisualEdit = () => useContext(VisualEditContext);

export const VisualEditProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [isEditing, setIsEditing] = useState(false);
  const [overrides, setOverrides] = useState<StyleOverride[]>([]);
  const [loading, setLoading] = useState(true);
  const location = useLocation();
  const observerRef = useRef<MutationObserver | null>(null);

  // 1. Activate Edit Mode from URL
  useEffect(() => {
    const params = new URLSearchParams(location.search);
    if (params.get('visualEdit') === 'true') {
      setIsEditing(true);
    } else {
      setIsEditing(false);
    }
  }, [location]);

  // 2. Fetch Overrides from Firebase on Mount
  useEffect(() => {
    const fetchOverrides = async () => {
      try {
        const doc = await db.collection('site_settings').doc('visual_overrides').get();
        if (doc.exists) {
          const data = doc.data();
          if (data && data.overrides) {
            console.log("Loaded overrides:", data.overrides);
            setOverrides(data.overrides);
          }
        }
      } catch (error) {
        console.error("Error loading visual overrides:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchOverrides();
  }, []);

  // 3. Inject CSS Styles into <head>
  useEffect(() => {
    const styleId = 'visual-editor-global-styles';
    let styleTag = document.getElementById(styleId);
    
    if (!styleTag) {
      styleTag = document.createElement('style');
      styleTag.id = styleId;
      document.head.appendChild(styleTag);
    }

    let css = '/* Generated by Shamsia Visual Editor */\n';
    overrides.forEach(item => {
      // Only generate CSS if there are styles
      if (item.styles && Object.keys(item.styles).length > 0) {
          const styleString = Object.entries(item.styles)
            .map(([key, value]) => {
                const val = value.includes('!important') ? value : `${value} !important`;
                return `${key}: ${val};`;
            })
            .join(' ');
          
          if (styleString) {
            css += `${item.selector} { ${styleString} }\n`;
          }
      }
    });

    styleTag.textContent = css;
  }, [overrides]);

  // 4. Apply Overrides using MutationObserver (Robust Text Persistence)
  useEffect(() => {
    const applyChanges = () => {
        overrides.forEach(override => {
            // Apply Text Changes
            if (override.text !== undefined && override.text !== null) {
                try {
                    const elements = document.querySelectorAll(override.selector);
                    elements.forEach(el => {
                        if (el instanceof HTMLElement) {
                             // Check if text is actually different to avoid infinite loops with Observer
                             if (el.innerText !== override.text) {
                                 // We use a flag to prevent fighting with our own updates if possible,
                                 // but with React re-renders, we force it.
                                 el.innerText = override.text as string;
                             }
                        }
                    });
                } catch (e) {
                    // Selector might be invalid or element not ready
                }
            }
        });
    };

    // Apply immediately
    applyChanges();

    // Setup Observer to re-apply on DOM changes (React renders, navigation)
    if (observerRef.current) {
        observerRef.current.disconnect();
    }

    observerRef.current = new MutationObserver((mutations) => {
        // Debounce logic could go here, but for text replacement, simpler is often better
        // We filter out mutations that we likely caused to avoid loop
        // But simply checking value equality inside applyChanges prevents the loop.
        applyChanges();
    });

    observerRef.current.observe(document.body, {
        childList: true,
        subtree: true,
        characterData: true
    });

    return () => {
        if (observerRef.current) {
            observerRef.current.disconnect();
        }
    };
  }, [overrides, location.pathname]);


  const saveOverride = (newOverride: StyleOverride) => {
    setOverrides(prev => {
      const updated = [...prev];
      const index = updated.findIndex(o => o.selector === newOverride.selector);
      
      if (index > -1) {
        updated[index] = {
            ...updated[index],
            styles: { ...updated[index].styles, ...newOverride.styles },
            text: newOverride.text !== undefined ? newOverride.text : updated[index].text
        };
      } else {
        updated.push(newOverride);
      }
      return updated;
    });
  };

  const saveAllChanges = async () => {
    try {
      const cleanOverrides = overrides.filter(o => 
        (o.styles && Object.keys(o.styles).length > 0) || (o.text !== undefined && o.text !== '')
      );
      
      await db.collection('site_settings').doc('visual_overrides').set(
        { overrides: cleanOverrides }, 
        { merge: true }
      );
      console.log("Visual overrides saved to Firebase successfully.");
    } catch (e) {
      console.error("Failed to save all changes to Firebase", e);
      throw e;
    }
  };

  const toggleEditMode = () => setIsEditing(!isEditing);

  return (
    <VisualEditContext.Provider value={{ isEditing, overrides, toggleEditMode, saveOverride, saveAllChanges, loading }}>
      {children}
    </VisualEditContext.Provider>
  );
};
